image: "python:3.7"

before_script:
  - python3.7 --version
  - pip3.7 install -r requirements.txt --user
  - export AWS_DIR="~/.aws/"

stages:
  - test
  - deploy

test:
  stage: test
  script:
  - cd tests
  - python3.7 testStockRetriever.py
