version: '3.5'

services:
    web:
        build:
          context: ./dashboard
          dockerfile: Dockerfile
        command: gunicorn dashboard.wsgi:application --bind 0.0.0.0:8000
        volumes:
            - static_volume:~/cs27-main/dashboard/static
        expose:
            - 8000
        env_file:
          - ./.env.prod
    nginx:
        build: ./nginx
        volumes:
            - static_volume:~/cs27-main/dashboard/static
        ports:
            - 80:80
        depends_on:
            - web
    py_code:
        build: .
        depends_on:
            - web

volumes:
    static_volume: