#!/bin/bash

if [ ! -f config.ini ]; then
    echo "Setting up config.ini for dns updates"
    python3 dns.py
fi

if [ "$1" != "" ]; then
    echo "Starting up the Driver..."
    python3 Driver.py $1
else
    echo "Positional parameter 1 is empty. (Must be \"amzn\", \"msft\", \"from_amzn\" or \"from_msft\")"
fi
