#!/bin/bash

if [ ! -f config.ini ]; then
    echo "Setting up config.ini for dns updates"
    python3 dns.py
fi

if [ "$1" != "" ]; then
    echo "Starting up the Driver..."
    python3 -m pip install -r requirements.txt
    if [ "$2" = "demo" ]; then # if the second argument is demo
	    sudo -E python3 Driver.py $1
    else
	    # does not output to screen but persists after session ends
	    # append it onto a seperate file that is not transferred
        # and also redirects errors to that output
	    sudo -E nohup python3 Driver.py $1 >> ../driver.out 2>&1 &
        cd dashboard
        sudo -E nohup ./deploy_web.sh >> ../deploy_web.out 2>&1 &
    fi
    
else
    echo "Positional parameter 1 is empty. Must be a stock name"
fi
