#!/bin/bash

if [ ! -f config.ini ]; then
    echo "Setting up config.ini for dns updates"
    python3 dns.py
fi

if [ "$1" != "" ]; then
    echo "Starting up the Driver..."
    python3 -m pip3 install -r ./requirements.txt
    if [ "$2" = "demo" ]; then # if the second argument is demo
	    python3 Driver.py $1
    else
	    # does not output to screen but persists after session ends
	    # append it onto a seperate file that is not transferred
        # and also redirects errors to that output
	    nohup python3 Driver.py $1 >> ../driver.out 2>&1 &
        cd dashboard
        nohup ./deploy_web.sh >> ../web_deploy.sh &
    fi
    
else
    echo "Positional parameter 1 is empty. (Must be \"amzn\", \"msft\", \"from_amzn\" or \"from_msft\")"
fi
