FROM python:3.8.0-alpine

WORKDIR /usr/src/dashboard

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt /usr/src/dashboard/requirements.txt
RUN pip install -r requirements.txt

COPY ./entrypoint.sh /usr/src/dashboard/entrypoint.sh
COPY . /usr/src/dashboard/

ENTRYPOINT ["/usr/src/dashboard/entrypoint.sh"]